name: Démo workflow Dotnet avec artéfact

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code source
        uses: actions/checkout@v6

      - name: Installation de Dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      
      - name: Installation des dépendances
        run: dotnet restore DemoGithubActions

      - name: Compilation du projet
        run: dotnet build DemoGithubActions --no-restore 

      - name: Publication du projet
        run: dotnet publish DemoGithubActions --no-build --configuration Debug -o ./publish

      - name: Upload artéfact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./publish/